In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
## Load all the Trained Model Scaler,encoded pickle and model files

## Model file
model=load_model('model.h5')

# Loading Label Encoder pickle file
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl','rb') as file:
    oh_geo=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
input_data={
    'CreditScore':600, 
    'Geography':'France',
      'Gender':'Male', 
      'Age':40,
        'Tenure':3, 
        'Balance':60000,
       'NumOfProducts':2,
         'HasCrCard':1,
           'IsActiveMember':1, 
           'EstimatedSalary':50000,
}

In [5]:
## one-hot Encode 'Geography'
geo_encoded=oh_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=oh_geo.get_feature_names_out(['Geography']))

e:\Project\ANNClassification\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [6]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [7]:
input_df=pd.DataFrame([input_data])

In [10]:
## Encoding the gender value
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [11]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [12]:
# Concatenation
input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [13]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [14]:
## Scaling the data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [15]:
## Predict churn
prediction=model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step

In [18]:
prediction_proba=prediction[0][0]
prediction_proba

0.08378122

In [21]:
if prediction_proba>0.5:
    print("The Customer is likely to churn")
else:
    print("The Customer is not likey to Churn")

The Customer is not likey to Churn